apiVersion: v1
kind: Template
metadata:
  name: php-app
  labels:
    app: php-app
parameters:
  - name: NAME
    displayName: Application Name
    description: The name of the application
    value: php-app
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL of the source repository for the application
    value: https://github.com/openshift/php-ex.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Source Repository Ref
    description: The branch, tag, or commit of the source repository
    value: master
  - name: APPLICATION_IMAGE
    displayName: Application Image
    description: The image name for the PHP application
    value: openshift/php:7.4

objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        app: ${NAME}
      template:
        metadata:
          labels:
            app: ${NAME}
        spec:
          containers:
            - name: php
              image: ${APPLICATION_IMAGE}
              ports:
                - containerPort: 8080
              env:
                - name: DATABASE_URL
                  value: "mysql://user:password@mysql-service:3306/mydatabase"
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      selector:
        app: ${NAME}
      ports:
        - port: 80
          targetPort: 8080
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      to:
        kind: Service
        name: ${NAME}
      port:
        targetPort: 8080
